[
    {
        "EQUIPMENT_NUM": "7230051040034CB117788",
        "EQUIPMENT_NAME": "GBCOM44",
        "MAC": "00-34-CB-11-77-88",
        "IP": "",
        "SECURITY_FACTORY_ORGCODE": "723005104",
        "VENDOR_NAME": "",
        "VENDOR_NUM": "",
        "SERVICE_CODE": "31011210001234",
        "PROVINCE_CODE": "310000",
        "CITY_CODE": "310000",
        "AREA_CODE": "310112",
        "INSTALL_DATE": "",
        "INSTALL_POINT": "",
        "EQUIPMENT_TYPE": "10",
        "LONGITUDE": "",
        "LATITUDE": "",
        "SUBWAY_STATION": "",
        "SUBWAY_LINE_INFO": "",
        "SUBWAY_VEHICLE_INFO": "",
        "SUBWAY_COMPARTMENT_NUM": "",
        "CAR_CODE": "",
        "UPLOAD_TIME_INTERVAL": "",
        "COLLECTION_RADIUS": "",
        "CREATE_TIME": "2016-12-09 22:37:21",
        "CREATER": "",
        "LAST_CONNECT_TIME": "",
        "REMARK": "",
        "WDA_VERSION": "",
        "FIRMWARE_VERSION": ""
    },
    {
        "EQUIPMENT_NUM": "7230051040034CB117733",
        "EQUIPMENT_NAME": "GBCOM",
        "MAC": "00-34-CB-11-77-33",
        "IP": "",
        "SECURITY_FACTORY_ORGCODE": "723005104",
        "VENDOR_NAME": "",
        "VENDOR_NUM": "",
        "SERVICE_CODE": "31011210001234",
        "PROVINCE_CODE": "310000",
        "CITY_CODE": "310000",
        "AREA_CODE": "310112",
        "INSTALL_DATE": "",
        "INSTALL_POINT": "",
        "EQUIPMENT_TYPE": "10",
        "LONGITUDE": "",
        "LATITUDE": "",
        "SUBWAY_STATION": "",
        "SUBWAY_LINE_INFO": "",
        "SUBWAY_VEHICLE_INFO": "",
        "SUBWAY_COMPARTMENT_NUM": "",
        "CAR_CODE": "",
        "UPLOAD_TIME_INTERVAL": "",
        "COLLECTION_RADIUS": "",
        "CREATE_TIME": "2016-12-09 22:37:21",
        "CREATER": "",
        "LAST_CONNECT_TIME": "",
        "REMARK": "",
        "WDA_VERSION": "",
        "FIRMWARE_VERSION": ""
    }
]
